[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GFX Library@^1.11.10
    adafruit/Adafruit ILI9341@^1.6.1
    adafruit/Adafruit FT6206 Library@^1.1.0
    adafruit/Adafruit NeoPixel@^1.12.3
    bblanchon/ArduinoJson@^7.2.1
build_flags =
    -D SERIAL_DEBUG=1
    -O2
